// ===== 食材定義 =====
// image: images フォルダに置く画像（無い場合は名前の頭文字を表示）
const ITEMS = [
  { id: "leek", name: "ふといながねぎ", image: "images/leek.png" },
  { id: "mushroom", name: "あじわいキノコ", image: "images/mushroom.png" },
  { id: "egg", name: "とくせんエッグ", image: "images/egg.png" },
  { id: "potato", name: "ほっこりポテト", image: "images/potato.png" },
  { id: "apple", name: "とくせんリンゴ", image: "images/apple.png" },
  { id: "herb", name: "げきからハーブ", image: "images/herb.png" },
  { id: "sausage", name: "マメミート", image: "images/sausage.png" },
  { id: "milk", name: "モーモーミルク", image: "images/milk.png" },
  { id: "honey", name: "あまいミツ", image: "images/honey.png" },
  { id: "oil", name: "ピュアなオイル", image: "images/oil.png" },
  { id: "ginger", name: "あったかジンジャー", image: "images/ginger.png" },
  { id: "tomato", name: "あんみんトマト", image: "images/tomato.png" },
  { id: "cacao", name: "リラックスカカオ", image: "images/cacao.png" },
  { id: "tail", name: "おいしいシッポ", image: "images/tail.png" },
  { id: "soy", name: "ワカクサ大豆", image: "images/soy.png" },
  { id: "corn", name: "ワカクサコーン", image: "images/corn.png" },
  { id: "coffee", name: "めざましコーヒー", image: "images/coffee.png" },
  { id: "pumpkin", name: "ずっしりカボチャ", image: "images/pumpkin.png" },
  { id: "avocado", name: "つやつやアボカド", image: "images/avocado.png" },
];

// ===== カテゴリ =====
const CATEGORIES = [
  { id: "curry", name: "カレー・シチュー" },
  { id: "salad", name: "サラダ" },
  { id: "dessert", name: "デザート・ドリンク" },
];

// ===== レシピ定義（出典: game8 ポケモンスリープ料理レシピ一覧） =====
// requires: { 食材id: 必要数, ... }
const RECIPES = [
  // --- curry ---
  { category: "curry", name: "とびはねるカレーうどん", requires: { sausage: 20, herb: 22, ginger: 39, mushroom: 31 } },
  { category: "curry", name: "しんりょくアボカドグラタン", requires: { milk: 41, potato: 20, oil: 32, avocado: 22 } },
  { category: "curry", name: "いあいぎりすき焼きカレー", requires: { sausage: 26, leek: 27, egg: 22, honey: 26 } },
  { category: "curry", name: "めざめるパワーシチュー", requires: { soy: 28, tomato: 25, mushroom: 23, coffee: 16 } },
  { category: "curry", name: "なりきりバケッチャシチュー", requires: { sausage: 16, potato: 18, mushroom: 25, pumpkin: 10 } },
  { category: "curry", name: "れんごくコーンキーマカレー", requires: { sausage: 24, herb: 27, ginger: 12, corn: 14 } },
  { category: "curry", name: "ワカクサカレーパン", requires: { soy: 8, oil: 15, herb: 20, ginger: 20 } },
  { category: "curry", name: "ニンジャカレー", requires: { soy: 24, sausage: 9, leek: 12, mushroom: 5 } },
  { category: "curry", name: "ぜったいねむりバターカレー", requires: { cacao: 12, milk: 10, potato: 18, tomato: 15 } },
  { category: "curry", name: "あぶりテールカレー", requires: { herb: 25, tail: 8 } },
  { category: "curry", name: "からくちネギもりカレー", requires: { leek: 14, herb: 8, ginger: 10 } },
  { category: "curry", name: "ピヨピヨパンチ辛口カレー", requires: { herb: 11, honey: 11, coffee: 11 } },
  { category: "curry", name: "じゅうなんコーンシチュー", requires: { milk: 8, potato: 8, corn: 14 } },
  { category: "curry", name: "おやこあいカレー", requires: { potato: 4, apple: 11, egg: 8, honey: 12 } },
  { category: "curry", name: "キノコのほうしカレー", requires: { potato: 9, mushroom: 14 } },
  { category: "curry", name: "ビルドアップマメカレー", requires: { soy: 12, sausage: 6, egg: 4, herb: 4 } },
  { category: "curry", name: "ほっこりホワイトシチュー", requires: { milk: 10, potato: 8, mushroom: 4 } },
  { category: "curry", name: "とけるオムカレー", requires: { egg: 10, tomato: 6 } },
  { category: "curry", name: "サンパワートマトカレー", requires: { herb: 5, tomato: 10 } },
  { category: "curry", name: "ひでりカツレツカレー", requires: { sausage: 10, oil: 5 } },
  { category: "curry", name: "満腹チーズバーグカレー", requires: { milk: 8, sausage: 8 } },
  { category: "curry", name: "マメバーグカレー", requires: { sausage: 7 } },
  { category: "curry", name: "ベイビィハニーカレー", requires: { honey: 7 } },
  { category: "curry", name: "たんじゅんホワイトシチュー", requires: { milk: 7 } },
  { category: "curry", name: "とくせんリンゴカレー", requires: { apple: 7 } },
  // --- salad ---
  { category: "salad", name: "ごろごろねっとうサラダ", requires: { potato: 30, mushroom: 27, corn: 18, pumpkin: 20 } },
  { category: "salad", name: "じならしワカモレチップス", requires: { soy: 22, herb: 30, corn: 25, avocado: 28 } },
  { category: "salad", name: "まけんきコーヒーサラダ", requires: { sausage: 28, potato: 22, oil: 22, coffee: 28 } },
  { category: "salad", name: "りんごさんヨーグルトサラダ", requires: { milk: 18, apple: 28, egg: 35, tomato: 23 } },
  { category: "salad", name: "はなふぶきミモザサラダ", requires: { sausage: 12, potato: 15, oil: 17, egg: 25 } },
  { category: "salad", name: "ニンジャサラダ", requires: { soy: 19, leek: 15, ginger: 11, mushroom: 12 } },
  { category: "salad", name: "ワカクササラダ", requires: { potato: 9, oil: 22, tomato: 14, corn: 17 } },
  { category: "salad", name: "クロスチョップドサラダ", requires: { sausage: 15, egg: 20, tomato: 10, corn: 11 } },
  { category: "salad", name: "ヤドンテールのペッパーサラダ", requires: { oil: 15, herb: 10, tail: 10 } },
  { category: "salad", name: "めいそうスイートサラダ", requires: { apple: 21, honey: 16, corn: 12 } },
  { category: "salad", name: "くだけるアボカドサラダ", requires: { soy: 18, oil: 10, avocado: 14 } },
  { category: "salad", name: "キノコのほうしサラダ", requires: { oil: 8, tomato: 8, mushroom: 17 } },
  { category: "salad", name: "オーバーヒートサラダ", requires: { herb: 17, tomato: 8, ginger: 10 } },
  { category: "salad", name: "くいしんぼうポテトサラダ", requires: { sausage: 7, potato: 14, apple: 6, egg: 9 } },
  { category: "salad", name: "ムラっけチョコミートサラダ", requires: { cacao: 14, sausage: 9 } },
  { category: "salad", name: "うるおいとうふサラダ", requires: { soy: 15, tomato: 9 } },
  { category: "salad", name: "ばかぢからワイルドサラダ", requires: { sausage: 9, potato: 3, egg: 5, ginger: 6 } },
  { category: "salad", name: "モーモーカプレーゼ", requires: { milk: 12, oil: 5, tomato: 6 } },
  { category: "salad", name: "めんえきねぎサラダ", requires: { leek: 10, ginger: 5 } },
  { category: "salad", name: "みだれづきコーンサラダ", requires: { oil: 8, corn: 9 } },
  { category: "salad", name: "メロメロりんごのチーズサラダ", requires: { milk: 5, oil: 3, apple: 15 } },
  { category: "salad", name: "ねっぷうとうふサラダ", requires: { soy: 10, herb: 6 } },
  { category: "salad", name: "ゆきかきシーザーサラダ", requires: { milk: 10, sausage: 6 } },
  { category: "salad", name: "あんみんトマトサラダ", requires: { tomato: 8 } },
  { category: "salad", name: "マメハムサラダ", requires: { sausage: 8 } },
  { category: "salad", name: "とくせんリンゴサラダ", requires: { apple: 8 } },
  // --- dessert ---
  { category: "dessert", name: "みつあつめチョコワッフル", requires: { cacao: 21, oil: 28, honey: 38, corn: 28 } },
  { category: "dessert", name: "ドキドキこわいかおパンケーキ", requires: { egg: 24, tomato: 29, honey: 32, pumpkin: 18 } },
  { category: "dessert", name: "ドオーのエクレア", requires: { cacao: 30, milk: 26, honey: 22, coffee: 24 } },
  { category: "dessert", name: "スパークスパイスコーラ", requires: { leek: 20, apple: 35, ginger: 20, coffee: 12 } },
  { category: "dessert", name: "フラワーギフトマカロン", requires: { cacao: 25, milk: 10, egg: 25, honey: 17 } },
  { category: "dessert", name: "おちゃかいコーンスコーン", requires: { milk: 9, apple: 20, ginger: 20, corn: 18 } },
  { category: "dessert", name: "グラスミキサースムージー", requires: { milk: 14, tomato: 16, avocado: 18 } },
  { category: "dessert", name: "プリンのプリンアラモード", requires: { milk: 10, apple: 10, egg: 15, honey: 20 } },
  { category: "dessert", name: "かたやぶりコーンティラミス", requires: { milk: 12, corn: 14, coffee: 14 } },
  { category: "dessert", name: "はやおきコーヒーゼリー", requires: { milk: 14, honey: 12, coffee: 16 } },
  { category: "dessert", name: "だいばくはつポップコーン", requires: { milk: 7, oil: 14, corn: 15 } },
  { category: "dessert", name: "ちからもちソイドーナッツ", requires: { soy: 16, cacao: 7, oil: 12 } },
  { category: "dessert", name: "ネロリのデトックスティー", requires: { apple: 15, ginger: 11, mushroom: 9 } },
  { category: "dessert", name: "ふくつのジンジャークッキー", requires: { cacao: 5, egg: 4, honey: 14, ginger: 12 } },
  { category: "dessert", name: "あくまのキッスフルーツオレ", requires: { cacao: 8, milk: 9, apple: 11, honey: 7 } },
  { category: "dessert", name: "あまいかおりチョコケーキ", requires: { cacao: 8, milk: 7, honey: 9 } },
  { category: "dessert", name: "はなびらのまいチョコタルト", requires: { cacao: 11, apple: 11 } },
  { category: "dessert", name: "はりきりプロテインスムージー", requires: { soy: 15, cacao: 8 } },
  { category: "dessert", name: "おおきいマラサダ", requires: { milk: 7, oil: 10, honey: 6 } },
  { category: "dessert", name: "マイペースやさいジュース", requires: { apple: 7, tomato: 9 } },
  { category: "dessert", name: "かるわざソイケーキ", requires: { soy: 7, egg: 8 } },
  { category: "dessert", name: "ひのこのジンジャーティー", requires: { apple: 7, ginger: 9 } },
  { category: "dessert", name: "じゅくせいスイートポテト", requires: { milk: 5, potato: 9 } },
  { category: "dessert", name: "ねがいごとアップルパイ", requires: { milk: 4, apple: 12 } },
  { category: "dessert", name: "クラフトサイコソーダ", requires: { honey: 9 } },
  { category: "dessert", name: "とくせんリンゴジュース", requires: { apple: 8 } },
  { category: "dessert", name: "モーモーホットミルク", requires: { milk: 7 } },
];
